-- Drop existing indexes on Batches table
SELECT CONCAT('DROP INDEX `', INDEX_NAME, '` ON `Batches`;')
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = 'Batches'
AND INDEX_NAME != 'PRIMARY';
